### ISSUE TITLE
Curious about why this works

### ISSUE THREAD

**Issue by codestiff** [pjstadig/ring-cider-debug#2]
Is there a blog or explanation on how it was concluded that:
```clojure
(defn wrap-cider-debug
  "Establishes thread local bindings necessary for CIDER debugging.  This should
  only be used in development, but it is safe to include even when cider-nrepl
  is not on the classpath.
  As of CIDER 0.20, when code instrumented for CIDER debugging is called outside
  of an nREPL request/response cycle (e.g. when called from a ring handler),
  there is some global state that is modified and can cause break points to no
  longer break.  Establishing a thread local binding for each ring request
  leaves the global state alone (as it should), and therefore break points work
  correctly."
  [handler]
  (let [*skip-breaks* (delay (try (ns-resolve 'cider.nrepl.middleware.debug '*skip-breaks*)
                                  (catch Exception _)))]
    (fn
      ([request]
       (if @*skip-breaks*
         (with-bindings* {@*skip-breaks* (atom nil)}
           handler request)
         (handler request)))
      ([request respond raise]
       (if @*skip-breaks*
         (with-bindings* {@*skip-breaks* (atom nil)}
           handler request respond raise)
         (handler request respond raise))))))
```

resolves break points not triggering when running ring apps (also other java server apps).

I found I could consistently get break points to trigger from other threads. The break points only consistently broke when running the app in jetty.

**Comment by codestiff** [comment]
> As of CIDER 0.20, when code instrumented for CIDER debugging is called outside
  of an nREPL request/response cycle (e.g. when called from a ring handler),
  there is some global state that is modified and can cause break points to no
  longer break.  Establishing a thread local binding for each ring request
  leaves the global state alone (as it should), and therefore break points work
  correctly.

I know that explains it, but I would like to know more if possible

**Comment by codestiff** [comment]
Ref: https://github.com/clojure-emacs/cider-nrepl/blob/v0.24.0/src/cider/nrepl/middleware/debug.clj#L58

**Comment by codestiff** [comment]
More concretely, where is there an example of the state `*skip-breaks*` being overridden?

**Comment by pjstadig** [comment]
If you are setting breakpoints in a thread that has been spawned from a REPL request thread, then it will inherit dynamic bindings, and you wouldn't see this issue.

The issue I was seeing specifically was when you continue a breakpoint using the 'C' command "Continue without stopping for all breakpoints" (for some reason this command does not show in the mode line, but it is documented).

Normally, when you execute code in a repl, `*skip-breaks*` is dynamically bound and set to an atom that tracks the state for that execution. However, a ring request does not do this, so the debugging state that is used is the root value of `*skip-breaks*`.

Continuing for all breakpoints would set a flag in the `*skip-breaks*` atom so that every future breakpoint would be skipped. If you do this once in a ring request, then the debugger would never break again, because the change was made in a root value of `*skip-breaks*`, and it is never bound to any other value.

This middleware will bind `*skip-breaks*` for each ring request. Then when you debug changes are made to the atom in the dynamic binding, which is used only for one ring request.

**Comment by codestiff** [comment]
Thank you! I may take a look at the `cider.nrepl` source to view the lifecycle of the `*skip-breaks*` var.

**Comment by codestiff** [comment]
Possibly related: https://github.com/clojure-emacs/cider/issues/1869
And: https://github.com/clojure-emacs/cider-nrepl/issues/460

**Comment by codestiff** [comment]
Example interceptor code for `pedestal`

```clojure
{:name ::cider-debug-breakpoints
 :enter (fn
         [ctx]
         (let [*skip-breaks* (delay
                               (try (ns-resolve 'cider.nrepl.middleware.debug '*skip-breaks*)
                                   catch Exception _)))]
            (assoc  ctx :bindings {@*skip-breaks* (atom nil)})))}
```

**Comment by pjstadig** [comment]
As mentioned in clojure-emacs/cider-nrepl#460 this may be fixed. I haven't verified with a recent version of cider.

**Comment by codestiff** [comment]
Confirmed not working as off: `"0.25.0-alpha1"`
